name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PLUGIN_NAME: obsidian-google-calendar-tasks-sync-plugin

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Package plugin
        run: |
          mkdir "$PLUGIN_NAME"
          cp main.js manifest.json styles.css "$PLUGIN_NAME"/
          zip -r "$PLUGIN_NAME.zip" "$PLUGIN_NAME"/

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${GITHUB_REF##*/}"
          gh release create "$TAG" \
            --title="Release $TAG" \
            --notes="New release of $PLUGIN_NAME" \
            --draft \
            "$PLUGIN_NAME.zip"

